FROM composer:latest AS composer

WORKDIR /var/www

COPY . .

RUN composer install --no-dev --optimize-autoloader

FROM php:8.2-apache

WORKDIR /var/www

COPY --from=composer /var/www /var/www

COPY .env.example .env

RUN apt-get update && apt-get install -y \
    git unzip zip libpq-dev libonig-dev libxml2-dev libzip-dev libpng-dev \
    && docker-php-ext-install pdo pdo_pgsql zip

RUN chown -R www-data:www-data /var/www && a2enmod rewrite

COPY ./docker/apache/vhost.conf /etc/apache2/sites-available/000-default.conf

# Générer la clé + migrer + lancer Apache
CMD php artisan key:generate && php artisan migrate --force && apache2-foreground
